package com.bestpay.ecurrency.operations.dal.mapper;

import com.bestpay.ecurrency.operations.dal.model.EoSymStaffRoleDOExample;
import com.bestpay.ecurrency.operations.dal.model.EoSymStaffRoleDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EoSymStaffRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    long countByExample(EoSymStaffRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    int deleteByExample(EoSymStaffRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    int deleteByPrimaryKey(EoSymStaffRoleDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    int insert(EoSymStaffRoleDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    int insertSelective(EoSymStaffRoleDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    List<EoSymStaffRoleDOKey> selectByExample(EoSymStaffRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") EoSymStaffRoleDOKey record, @Param("example") EoSymStaffRoleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EO_SYM_STAFFROLE
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    int updateByExample(@Param("record") EoSymStaffRoleDOKey record, @Param("example") EoSymStaffRoleDOExample example);
}