package com.bestpay.ecurrency.operations.dal.mapper;

import com.bestpay.ecurrency.operations.dal.model.PcmAcctinfoDO;
import com.bestpay.ecurrency.operations.dal.model.PcmAcctinfoDOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PcmAcctinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    long countByExample(PcmAcctinfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    int insert(PcmAcctinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    int insertSelective(PcmAcctinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    List<PcmAcctinfoDO> selectByExample(PcmAcctinfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    PcmAcctinfoDO selectByPrimaryKey(String acctCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") PcmAcctinfoDO record, @Param("example") PcmAcctinfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    int updateByExample(@Param("record") PcmAcctinfoDO record, @Param("example") PcmAcctinfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    int updateByPrimaryKeySelective(PcmAcctinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    int updateByPrimaryKey(PcmAcctinfoDO record);
}