package com.bestpay.ecurrency.operations.dal.model;

public class EoSymStaffRoleDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EO_SYM_STAFFROLE.STAFF_ID
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EO_SYM_STAFFROLE.ROLE_ID
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EO_SYM_STAFFROLE.STAFF_ID
     *
     * @return the value of T_EO_SYM_STAFFROLE.STAFF_ID
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EO_SYM_STAFFROLE.STAFF_ID
     *
     * @param staffId the value for T_EO_SYM_STAFFROLE.STAFF_ID
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EO_SYM_STAFFROLE.ROLE_ID
     *
     * @return the value of T_EO_SYM_STAFFROLE.ROLE_ID
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EO_SYM_STAFFROLE.ROLE_ID
     *
     * @param roleId the value for T_EO_SYM_STAFFROLE.ROLE_ID
     *
     * @mbg.generated Wed Nov 23 13:37:51 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}