package com.bestpay.ecurrency.operations.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PcmAcctinfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public PcmAcctinfoDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAcctCodeIsNull() {
            addCriterion("ACCT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAcctCodeIsNotNull() {
            addCriterion("ACCT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAcctCodeEqualTo(String value) {
            addCriterion("ACCT_CODE =", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeNotEqualTo(String value) {
            addCriterion("ACCT_CODE <>", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeGreaterThan(String value) {
            addCriterion("ACCT_CODE >", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_CODE >=", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeLessThan(String value) {
            addCriterion("ACCT_CODE <", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeLessThanOrEqualTo(String value) {
            addCriterion("ACCT_CODE <=", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeLike(String value) {
            addCriterion("ACCT_CODE like", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeNotLike(String value) {
            addCriterion("ACCT_CODE not like", value, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeIn(List<String> values) {
            addCriterion("ACCT_CODE in", values, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeNotIn(List<String> values) {
            addCriterion("ACCT_CODE not in", values, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeBetween(String value1, String value2) {
            addCriterion("ACCT_CODE between", value1, value2, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctCodeNotBetween(String value1, String value2) {
            addCriterion("ACCT_CODE not between", value1, value2, "acctCode");
            return (Criteria) this;
        }

        public Criteria andAcctTypeIsNull() {
            addCriterion("ACCT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAcctTypeIsNotNull() {
            addCriterion("ACCT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAcctTypeEqualTo(String value) {
            addCriterion("ACCT_TYPE =", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeNotEqualTo(String value) {
            addCriterion("ACCT_TYPE <>", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeGreaterThan(String value) {
            addCriterion("ACCT_TYPE >", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_TYPE >=", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeLessThan(String value) {
            addCriterion("ACCT_TYPE <", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeLessThanOrEqualTo(String value) {
            addCriterion("ACCT_TYPE <=", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeLike(String value) {
            addCriterion("ACCT_TYPE like", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeNotLike(String value) {
            addCriterion("ACCT_TYPE not like", value, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeIn(List<String> values) {
            addCriterion("ACCT_TYPE in", values, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeNotIn(List<String> values) {
            addCriterion("ACCT_TYPE not in", values, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeBetween(String value1, String value2) {
            addCriterion("ACCT_TYPE between", value1, value2, "acctType");
            return (Criteria) this;
        }

        public Criteria andAcctTypeNotBetween(String value1, String value2) {
            addCriterion("ACCT_TYPE not between", value1, value2, "acctType");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNull() {
            addCriterion("CURRENCY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNotNull() {
            addCriterion("CURRENCY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeEqualTo(String value) {
            addCriterion("CURRENCY_CODE =", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotEqualTo(String value) {
            addCriterion("CURRENCY_CODE <>", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThan(String value) {
            addCriterion("CURRENCY_CODE >", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY_CODE >=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThan(String value) {
            addCriterion("CURRENCY_CODE <", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY_CODE <=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLike(String value) {
            addCriterion("CURRENCY_CODE like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotLike(String value) {
            addCriterion("CURRENCY_CODE not like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIn(List<String> values) {
            addCriterion("CURRENCY_CODE in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotIn(List<String> values) {
            addCriterion("CURRENCY_CODE not in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeBetween(String value1, String value2) {
            addCriterion("CURRENCY_CODE between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("CURRENCY_CODE not between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitIsNull() {
            addCriterion("CURRENCY_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitIsNotNull() {
            addCriterion("CURRENCY_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitEqualTo(String value) {
            addCriterion("CURRENCY_UNIT =", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitNotEqualTo(String value) {
            addCriterion("CURRENCY_UNIT <>", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitGreaterThan(String value) {
            addCriterion("CURRENCY_UNIT >", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY_UNIT >=", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitLessThan(String value) {
            addCriterion("CURRENCY_UNIT <", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY_UNIT <=", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitLike(String value) {
            addCriterion("CURRENCY_UNIT like", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitNotLike(String value) {
            addCriterion("CURRENCY_UNIT not like", value, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitIn(List<String> values) {
            addCriterion("CURRENCY_UNIT in", values, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitNotIn(List<String> values) {
            addCriterion("CURRENCY_UNIT not in", values, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitBetween(String value1, String value2) {
            addCriterion("CURRENCY_UNIT between", value1, value2, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andCurrencyUnitNotBetween(String value1, String value2) {
            addCriterion("CURRENCY_UNIT not between", value1, value2, "currencyUnit");
            return (Criteria) this;
        }

        public Criteria andAcctPwdIsNull() {
            addCriterion("ACCT_PWD is null");
            return (Criteria) this;
        }

        public Criteria andAcctPwdIsNotNull() {
            addCriterion("ACCT_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andAcctPwdEqualTo(String value) {
            addCriterion("ACCT_PWD =", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdNotEqualTo(String value) {
            addCriterion("ACCT_PWD <>", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdGreaterThan(String value) {
            addCriterion("ACCT_PWD >", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_PWD >=", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdLessThan(String value) {
            addCriterion("ACCT_PWD <", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdLessThanOrEqualTo(String value) {
            addCriterion("ACCT_PWD <=", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdLike(String value) {
            addCriterion("ACCT_PWD like", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdNotLike(String value) {
            addCriterion("ACCT_PWD not like", value, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdIn(List<String> values) {
            addCriterion("ACCT_PWD in", values, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdNotIn(List<String> values) {
            addCriterion("ACCT_PWD not in", values, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdBetween(String value1, String value2) {
            addCriterion("ACCT_PWD between", value1, value2, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andAcctPwdNotBetween(String value1, String value2) {
            addCriterion("ACCT_PWD not between", value1, value2, "acctPwd");
            return (Criteria) this;
        }

        public Criteria andTimeLmtIsNull() {
            addCriterion("TIME_LMT is null");
            return (Criteria) this;
        }

        public Criteria andTimeLmtIsNotNull() {
            addCriterion("TIME_LMT is not null");
            return (Criteria) this;
        }

        public Criteria andTimeLmtEqualTo(Long value) {
            addCriterion("TIME_LMT =", value, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtNotEqualTo(Long value) {
            addCriterion("TIME_LMT <>", value, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtGreaterThan(Long value) {
            addCriterion("TIME_LMT >", value, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtGreaterThanOrEqualTo(Long value) {
            addCriterion("TIME_LMT >=", value, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtLessThan(Long value) {
            addCriterion("TIME_LMT <", value, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtLessThanOrEqualTo(Long value) {
            addCriterion("TIME_LMT <=", value, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtIn(List<Long> values) {
            addCriterion("TIME_LMT in", values, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtNotIn(List<Long> values) {
            addCriterion("TIME_LMT not in", values, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtBetween(Long value1, Long value2) {
            addCriterion("TIME_LMT between", value1, value2, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andTimeLmtNotBetween(Long value1, Long value2) {
            addCriterion("TIME_LMT not between", value1, value2, "timeLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtIsNull() {
            addCriterion("DAY_LMT is null");
            return (Criteria) this;
        }

        public Criteria andDayLmtIsNotNull() {
            addCriterion("DAY_LMT is not null");
            return (Criteria) this;
        }

        public Criteria andDayLmtEqualTo(Long value) {
            addCriterion("DAY_LMT =", value, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtNotEqualTo(Long value) {
            addCriterion("DAY_LMT <>", value, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtGreaterThan(Long value) {
            addCriterion("DAY_LMT >", value, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtGreaterThanOrEqualTo(Long value) {
            addCriterion("DAY_LMT >=", value, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtLessThan(Long value) {
            addCriterion("DAY_LMT <", value, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtLessThanOrEqualTo(Long value) {
            addCriterion("DAY_LMT <=", value, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtIn(List<Long> values) {
            addCriterion("DAY_LMT in", values, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtNotIn(List<Long> values) {
            addCriterion("DAY_LMT not in", values, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtBetween(Long value1, Long value2) {
            addCriterion("DAY_LMT between", value1, value2, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andDayLmtNotBetween(Long value1, Long value2) {
            addCriterion("DAY_LMT not between", value1, value2, "dayLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtIsNull() {
            addCriterion("TOTAL_LMT is null");
            return (Criteria) this;
        }

        public Criteria andTotalLmtIsNotNull() {
            addCriterion("TOTAL_LMT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalLmtEqualTo(Long value) {
            addCriterion("TOTAL_LMT =", value, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtNotEqualTo(Long value) {
            addCriterion("TOTAL_LMT <>", value, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtGreaterThan(Long value) {
            addCriterion("TOTAL_LMT >", value, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtGreaterThanOrEqualTo(Long value) {
            addCriterion("TOTAL_LMT >=", value, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtLessThan(Long value) {
            addCriterion("TOTAL_LMT <", value, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtLessThanOrEqualTo(Long value) {
            addCriterion("TOTAL_LMT <=", value, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtIn(List<Long> values) {
            addCriterion("TOTAL_LMT in", values, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtNotIn(List<Long> values) {
            addCriterion("TOTAL_LMT not in", values, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtBetween(Long value1, Long value2) {
            addCriterion("TOTAL_LMT between", value1, value2, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalLmtNotBetween(Long value1, Long value2) {
            addCriterion("TOTAL_LMT not between", value1, value2, "totalLmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalIsNull() {
            addCriterion("TOTAL_BAL is null");
            return (Criteria) this;
        }

        public Criteria andTotalBalIsNotNull() {
            addCriterion("TOTAL_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andTotalBalEqualTo(Long value) {
            addCriterion("TOTAL_BAL =", value, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalNotEqualTo(Long value) {
            addCriterion("TOTAL_BAL <>", value, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalGreaterThan(Long value) {
            addCriterion("TOTAL_BAL >", value, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalGreaterThanOrEqualTo(Long value) {
            addCriterion("TOTAL_BAL >=", value, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalLessThan(Long value) {
            addCriterion("TOTAL_BAL <", value, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalLessThanOrEqualTo(Long value) {
            addCriterion("TOTAL_BAL <=", value, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalIn(List<Long> values) {
            addCriterion("TOTAL_BAL in", values, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalNotIn(List<Long> values) {
            addCriterion("TOTAL_BAL not in", values, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalBetween(Long value1, Long value2) {
            addCriterion("TOTAL_BAL between", value1, value2, "totalBal");
            return (Criteria) this;
        }

        public Criteria andTotalBalNotBetween(Long value1, Long value2) {
            addCriterion("TOTAL_BAL not between", value1, value2, "totalBal");
            return (Criteria) this;
        }

        public Criteria andValidBalIsNull() {
            addCriterion("VALID_BAL is null");
            return (Criteria) this;
        }

        public Criteria andValidBalIsNotNull() {
            addCriterion("VALID_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andValidBalEqualTo(Long value) {
            addCriterion("VALID_BAL =", value, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalNotEqualTo(Long value) {
            addCriterion("VALID_BAL <>", value, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalGreaterThan(Long value) {
            addCriterion("VALID_BAL >", value, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalGreaterThanOrEqualTo(Long value) {
            addCriterion("VALID_BAL >=", value, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalLessThan(Long value) {
            addCriterion("VALID_BAL <", value, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalLessThanOrEqualTo(Long value) {
            addCriterion("VALID_BAL <=", value, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalIn(List<Long> values) {
            addCriterion("VALID_BAL in", values, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalNotIn(List<Long> values) {
            addCriterion("VALID_BAL not in", values, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalBetween(Long value1, Long value2) {
            addCriterion("VALID_BAL between", value1, value2, "validBal");
            return (Criteria) this;
        }

        public Criteria andValidBalNotBetween(Long value1, Long value2) {
            addCriterion("VALID_BAL not between", value1, value2, "validBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalIsNull() {
            addCriterion("FROZEN_BAL is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalIsNotNull() {
            addCriterion("FROZEN_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalEqualTo(Long value) {
            addCriterion("FROZEN_BAL =", value, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalNotEqualTo(Long value) {
            addCriterion("FROZEN_BAL <>", value, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalGreaterThan(Long value) {
            addCriterion("FROZEN_BAL >", value, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalGreaterThanOrEqualTo(Long value) {
            addCriterion("FROZEN_BAL >=", value, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalLessThan(Long value) {
            addCriterion("FROZEN_BAL <", value, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalLessThanOrEqualTo(Long value) {
            addCriterion("FROZEN_BAL <=", value, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalIn(List<Long> values) {
            addCriterion("FROZEN_BAL in", values, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalNotIn(List<Long> values) {
            addCriterion("FROZEN_BAL not in", values, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalBetween(Long value1, Long value2) {
            addCriterion("FROZEN_BAL between", value1, value2, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andFrozenBalNotBetween(Long value1, Long value2) {
            addCriterion("FROZEN_BAL not between", value1, value2, "frozenBal");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("STAT is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("STAT is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(String value) {
            addCriterion("STAT =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(String value) {
            addCriterion("STAT <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(String value) {
            addCriterion("STAT >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(String value) {
            addCriterion("STAT >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(String value) {
            addCriterion("STAT <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(String value) {
            addCriterion("STAT <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLike(String value) {
            addCriterion("STAT like", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotLike(String value) {
            addCriterion("STAT not like", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<String> values) {
            addCriterion("STAT in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<String> values) {
            addCriterion("STAT not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(String value1, String value2) {
            addCriterion("STAT between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(String value1, String value2) {
            addCriterion("STAT not between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatReasonIsNull() {
            addCriterion("STAT_REASON is null");
            return (Criteria) this;
        }

        public Criteria andStatReasonIsNotNull() {
            addCriterion("STAT_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andStatReasonEqualTo(String value) {
            addCriterion("STAT_REASON =", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonNotEqualTo(String value) {
            addCriterion("STAT_REASON <>", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonGreaterThan(String value) {
            addCriterion("STAT_REASON >", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonGreaterThanOrEqualTo(String value) {
            addCriterion("STAT_REASON >=", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonLessThan(String value) {
            addCriterion("STAT_REASON <", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonLessThanOrEqualTo(String value) {
            addCriterion("STAT_REASON <=", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonLike(String value) {
            addCriterion("STAT_REASON like", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonNotLike(String value) {
            addCriterion("STAT_REASON not like", value, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonIn(List<String> values) {
            addCriterion("STAT_REASON in", values, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonNotIn(List<String> values) {
            addCriterion("STAT_REASON not in", values, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonBetween(String value1, String value2) {
            addCriterion("STAT_REASON between", value1, value2, "statReason");
            return (Criteria) this;
        }

        public Criteria andStatReasonNotBetween(String value1, String value2) {
            addCriterion("STAT_REASON not between", value1, value2, "statReason");
            return (Criteria) this;
        }

        public Criteria andEffDateIsNull() {
            addCriterion("EFF_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEffDateIsNotNull() {
            addCriterion("EFF_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffDateEqualTo(Date value) {
            addCriterion("EFF_DATE =", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateNotEqualTo(Date value) {
            addCriterion("EFF_DATE <>", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateGreaterThan(Date value) {
            addCriterion("EFF_DATE >", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EFF_DATE >=", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateLessThan(Date value) {
            addCriterion("EFF_DATE <", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateLessThanOrEqualTo(Date value) {
            addCriterion("EFF_DATE <=", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateIn(List<Date> values) {
            addCriterion("EFF_DATE in", values, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateNotIn(List<Date> values) {
            addCriterion("EFF_DATE not in", values, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateBetween(Date value1, Date value2) {
            addCriterion("EFF_DATE between", value1, value2, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateNotBetween(Date value1, Date value2) {
            addCriterion("EFF_DATE not between", value1, value2, "effDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNull() {
            addCriterion("EXP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNotNull() {
            addCriterion("EXP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpDateEqualTo(Date value) {
            addCriterion("EXP_DATE =", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotEqualTo(Date value) {
            addCriterion("EXP_DATE <>", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThan(Date value) {
            addCriterion("EXP_DATE >", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE >=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThan(Date value) {
            addCriterion("EXP_DATE <", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE <=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIn(List<Date> values) {
            addCriterion("EXP_DATE in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotIn(List<Date> values) {
            addCriterion("EXP_DATE not in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE not between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andInitBalIsNull() {
            addCriterion("INIT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andInitBalIsNotNull() {
            addCriterion("INIT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andInitBalEqualTo(Long value) {
            addCriterion("INIT_BAL =", value, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalNotEqualTo(Long value) {
            addCriterion("INIT_BAL <>", value, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalGreaterThan(Long value) {
            addCriterion("INIT_BAL >", value, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalGreaterThanOrEqualTo(Long value) {
            addCriterion("INIT_BAL >=", value, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalLessThan(Long value) {
            addCriterion("INIT_BAL <", value, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalLessThanOrEqualTo(Long value) {
            addCriterion("INIT_BAL <=", value, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalIn(List<Long> values) {
            addCriterion("INIT_BAL in", values, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalNotIn(List<Long> values) {
            addCriterion("INIT_BAL not in", values, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalBetween(Long value1, Long value2) {
            addCriterion("INIT_BAL between", value1, value2, "initBal");
            return (Criteria) this;
        }

        public Criteria andInitBalNotBetween(Long value1, Long value2) {
            addCriterion("INIT_BAL not between", value1, value2, "initBal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 21 15:01:00 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PCM_ACCTINFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}