package com.bestpay.ecurrency.operations.dal.model;

import java.util.Date;

public class PcmAcctinfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.ACCT_CODE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String acctCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.ACCT_TYPE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String acctType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.CURRENCY_CODE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.CURRENCY_UNIT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String currencyUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.ACCT_PWD
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String acctPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.TIME_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long timeLmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.DAY_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long dayLmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.TOTAL_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long totalLmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.TOTAL_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long totalBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.VALID_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long validBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.FROZEN_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long frozenBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.STAT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String stat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.STAT_REASON
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String statReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.EFF_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.EXP_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_ACCTINFO.INIT_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long initBal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.ACCT_CODE
     *
     * @return the value of T_PCM_ACCTINFO.ACCT_CODE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getAcctCode() {
        return acctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.ACCT_CODE
     *
     * @param acctCode the value for T_PCM_ACCTINFO.ACCT_CODE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setAcctCode(String acctCode) {
        this.acctCode = acctCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.ACCT_TYPE
     *
     * @return the value of T_PCM_ACCTINFO.ACCT_TYPE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getAcctType() {
        return acctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.ACCT_TYPE
     *
     * @param acctType the value for T_PCM_ACCTINFO.ACCT_TYPE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setAcctType(String acctType) {
        this.acctType = acctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.CURRENCY_CODE
     *
     * @return the value of T_PCM_ACCTINFO.CURRENCY_CODE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.CURRENCY_CODE
     *
     * @param currencyCode the value for T_PCM_ACCTINFO.CURRENCY_CODE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.CURRENCY_UNIT
     *
     * @return the value of T_PCM_ACCTINFO.CURRENCY_UNIT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getCurrencyUnit() {
        return currencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.CURRENCY_UNIT
     *
     * @param currencyUnit the value for T_PCM_ACCTINFO.CURRENCY_UNIT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCurrencyUnit(String currencyUnit) {
        this.currencyUnit = currencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.ACCT_PWD
     *
     * @return the value of T_PCM_ACCTINFO.ACCT_PWD
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getAcctPwd() {
        return acctPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.ACCT_PWD
     *
     * @param acctPwd the value for T_PCM_ACCTINFO.ACCT_PWD
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setAcctPwd(String acctPwd) {
        this.acctPwd = acctPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.TIME_LMT
     *
     * @return the value of T_PCM_ACCTINFO.TIME_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getTimeLmt() {
        return timeLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.TIME_LMT
     *
     * @param timeLmt the value for T_PCM_ACCTINFO.TIME_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setTimeLmt(Long timeLmt) {
        this.timeLmt = timeLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.DAY_LMT
     *
     * @return the value of T_PCM_ACCTINFO.DAY_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getDayLmt() {
        return dayLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.DAY_LMT
     *
     * @param dayLmt the value for T_PCM_ACCTINFO.DAY_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setDayLmt(Long dayLmt) {
        this.dayLmt = dayLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.TOTAL_LMT
     *
     * @return the value of T_PCM_ACCTINFO.TOTAL_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getTotalLmt() {
        return totalLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.TOTAL_LMT
     *
     * @param totalLmt the value for T_PCM_ACCTINFO.TOTAL_LMT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setTotalLmt(Long totalLmt) {
        this.totalLmt = totalLmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.TOTAL_BAL
     *
     * @return the value of T_PCM_ACCTINFO.TOTAL_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getTotalBal() {
        return totalBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.TOTAL_BAL
     *
     * @param totalBal the value for T_PCM_ACCTINFO.TOTAL_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setTotalBal(Long totalBal) {
        this.totalBal = totalBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.VALID_BAL
     *
     * @return the value of T_PCM_ACCTINFO.VALID_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getValidBal() {
        return validBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.VALID_BAL
     *
     * @param validBal the value for T_PCM_ACCTINFO.VALID_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setValidBal(Long validBal) {
        this.validBal = validBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.FROZEN_BAL
     *
     * @return the value of T_PCM_ACCTINFO.FROZEN_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getFrozenBal() {
        return frozenBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.FROZEN_BAL
     *
     * @param frozenBal the value for T_PCM_ACCTINFO.FROZEN_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setFrozenBal(Long frozenBal) {
        this.frozenBal = frozenBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.STAT
     *
     * @return the value of T_PCM_ACCTINFO.STAT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.STAT
     *
     * @param stat the value for T_PCM_ACCTINFO.STAT
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.STAT_REASON
     *
     * @return the value of T_PCM_ACCTINFO.STAT_REASON
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getStatReason() {
        return statReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.STAT_REASON
     *
     * @param statReason the value for T_PCM_ACCTINFO.STAT_REASON
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setStatReason(String statReason) {
        this.statReason = statReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.EFF_DATE
     *
     * @return the value of T_PCM_ACCTINFO.EFF_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.EFF_DATE
     *
     * @param effDate the value for T_PCM_ACCTINFO.EFF_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.EXP_DATE
     *
     * @return the value of T_PCM_ACCTINFO.EXP_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.EXP_DATE
     *
     * @param expDate the value for T_PCM_ACCTINFO.EXP_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_ACCTINFO.INIT_BAL
     *
     * @return the value of T_PCM_ACCTINFO.INIT_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getInitBal() {
        return initBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_ACCTINFO.INIT_BAL
     *
     * @param initBal the value for T_PCM_ACCTINFO.INIT_BAL
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setInitBal(Long initBal) {
        this.initBal = initBal;
    }
}