package com.bestpay.ecurrency.operations.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PcmInfoDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public PcmInfoDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCardNoIsNull() {
            addCriterion("CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("CARD_NO =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("CARD_NO <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("CARD_NO >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NO >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("CARD_NO <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("CARD_NO <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("CARD_NO like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("CARD_NO not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("CARD_NO in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("CARD_NO not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("CARD_NO between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("CARD_NO not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdIsNull() {
            addCriterion("CARD_SEQ_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdIsNotNull() {
            addCriterion("CARD_SEQ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdEqualTo(String value) {
            addCriterion("CARD_SEQ_ID =", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdNotEqualTo(String value) {
            addCriterion("CARD_SEQ_ID <>", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdGreaterThan(String value) {
            addCriterion("CARD_SEQ_ID >", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_SEQ_ID >=", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdLessThan(String value) {
            addCriterion("CARD_SEQ_ID <", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdLessThanOrEqualTo(String value) {
            addCriterion("CARD_SEQ_ID <=", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdLike(String value) {
            addCriterion("CARD_SEQ_ID like", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdNotLike(String value) {
            addCriterion("CARD_SEQ_ID not like", value, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdIn(List<String> values) {
            addCriterion("CARD_SEQ_ID in", values, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdNotIn(List<String> values) {
            addCriterion("CARD_SEQ_ID not in", values, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdBetween(String value1, String value2) {
            addCriterion("CARD_SEQ_ID between", value1, value2, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardSeqIdNotBetween(String value1, String value2) {
            addCriterion("CARD_SEQ_ID not between", value1, value2, "cardSeqId");
            return (Criteria) this;
        }

        public Criteria andCardStateIsNull() {
            addCriterion("CARD_STATE is null");
            return (Criteria) this;
        }

        public Criteria andCardStateIsNotNull() {
            addCriterion("CARD_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andCardStateEqualTo(String value) {
            addCriterion("CARD_STATE =", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotEqualTo(String value) {
            addCriterion("CARD_STATE <>", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateGreaterThan(String value) {
            addCriterion("CARD_STATE >", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_STATE >=", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateLessThan(String value) {
            addCriterion("CARD_STATE <", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateLessThanOrEqualTo(String value) {
            addCriterion("CARD_STATE <=", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateLike(String value) {
            addCriterion("CARD_STATE like", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotLike(String value) {
            addCriterion("CARD_STATE not like", value, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateIn(List<String> values) {
            addCriterion("CARD_STATE in", values, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotIn(List<String> values) {
            addCriterion("CARD_STATE not in", values, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateBetween(String value1, String value2) {
            addCriterion("CARD_STATE between", value1, value2, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardStateNotBetween(String value1, String value2) {
            addCriterion("CARD_STATE not between", value1, value2, "cardState");
            return (Criteria) this;
        }

        public Criteria andCardPwdIsNull() {
            addCriterion("CARD_PWD is null");
            return (Criteria) this;
        }

        public Criteria andCardPwdIsNotNull() {
            addCriterion("CARD_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andCardPwdEqualTo(String value) {
            addCriterion("CARD_PWD =", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdNotEqualTo(String value) {
            addCriterion("CARD_PWD <>", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdGreaterThan(String value) {
            addCriterion("CARD_PWD >", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_PWD >=", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdLessThan(String value) {
            addCriterion("CARD_PWD <", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdLessThanOrEqualTo(String value) {
            addCriterion("CARD_PWD <=", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdLike(String value) {
            addCriterion("CARD_PWD like", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdNotLike(String value) {
            addCriterion("CARD_PWD not like", value, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdIn(List<String> values) {
            addCriterion("CARD_PWD in", values, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdNotIn(List<String> values) {
            addCriterion("CARD_PWD not in", values, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdBetween(String value1, String value2) {
            addCriterion("CARD_PWD between", value1, value2, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardPwdNotBetween(String value1, String value2) {
            addCriterion("CARD_PWD not between", value1, value2, "cardPwd");
            return (Criteria) this;
        }

        public Criteria andCardValueIsNull() {
            addCriterion("CARD_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andCardValueIsNotNull() {
            addCriterion("CARD_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andCardValueEqualTo(Long value) {
            addCriterion("CARD_VALUE =", value, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueNotEqualTo(Long value) {
            addCriterion("CARD_VALUE <>", value, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueGreaterThan(Long value) {
            addCriterion("CARD_VALUE >", value, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueGreaterThanOrEqualTo(Long value) {
            addCriterion("CARD_VALUE >=", value, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueLessThan(Long value) {
            addCriterion("CARD_VALUE <", value, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueLessThanOrEqualTo(Long value) {
            addCriterion("CARD_VALUE <=", value, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueIn(List<Long> values) {
            addCriterion("CARD_VALUE in", values, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueNotIn(List<Long> values) {
            addCriterion("CARD_VALUE not in", values, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueBetween(Long value1, Long value2) {
            addCriterion("CARD_VALUE between", value1, value2, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCardValueNotBetween(Long value1, Long value2) {
            addCriterion("CARD_VALUE not between", value1, value2, "cardValue");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNull() {
            addCriterion("EXP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNotNull() {
            addCriterion("EXP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpDateEqualTo(Date value) {
            addCriterion("EXP_DATE =", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotEqualTo(Date value) {
            addCriterion("EXP_DATE <>", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThan(Date value) {
            addCriterion("EXP_DATE >", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE >=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThan(Date value) {
            addCriterion("EXP_DATE <", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE <=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIn(List<Date> values) {
            addCriterion("EXP_DATE in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotIn(List<Date> values) {
            addCriterion("EXP_DATE not in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE not between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andEffDateIsNull() {
            addCriterion("EFF_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEffDateIsNotNull() {
            addCriterion("EFF_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffDateEqualTo(Date value) {
            addCriterion("EFF_DATE =", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateNotEqualTo(Date value) {
            addCriterion("EFF_DATE <>", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateGreaterThan(Date value) {
            addCriterion("EFF_DATE >", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EFF_DATE >=", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateLessThan(Date value) {
            addCriterion("EFF_DATE <", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateLessThanOrEqualTo(Date value) {
            addCriterion("EFF_DATE <=", value, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateIn(List<Date> values) {
            addCriterion("EFF_DATE in", values, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateNotIn(List<Date> values) {
            addCriterion("EFF_DATE not in", values, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateBetween(Date value1, Date value2) {
            addCriterion("EFF_DATE between", value1, value2, "effDate");
            return (Criteria) this;
        }

        public Criteria andEffDateNotBetween(Date value1, Date value2) {
            addCriterion("EFF_DATE not between", value1, value2, "effDate");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdIsNull() {
            addCriterion("CARD_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdIsNotNull() {
            addCriterion("CARD_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdEqualTo(Integer value) {
            addCriterion("CARD_TYPE_ID =", value, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdNotEqualTo(Integer value) {
            addCriterion("CARD_TYPE_ID <>", value, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdGreaterThan(Integer value) {
            addCriterion("CARD_TYPE_ID >", value, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CARD_TYPE_ID >=", value, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdLessThan(Integer value) {
            addCriterion("CARD_TYPE_ID <", value, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("CARD_TYPE_ID <=", value, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdIn(List<Integer> values) {
            addCriterion("CARD_TYPE_ID in", values, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdNotIn(List<Integer> values) {
            addCriterion("CARD_TYPE_ID not in", values, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("CARD_TYPE_ID between", value1, value2, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andCardTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CARD_TYPE_ID not between", value1, value2, "cardTypeId");
            return (Criteria) this;
        }

        public Criteria andProlongFlagIsNull() {
            addCriterion("PROLONG_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andProlongFlagIsNotNull() {
            addCriterion("PROLONG_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andProlongFlagEqualTo(Short value) {
            addCriterion("PROLONG_FLAG =", value, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagNotEqualTo(Short value) {
            addCriterion("PROLONG_FLAG <>", value, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagGreaterThan(Short value) {
            addCriterion("PROLONG_FLAG >", value, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("PROLONG_FLAG >=", value, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagLessThan(Short value) {
            addCriterion("PROLONG_FLAG <", value, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagLessThanOrEqualTo(Short value) {
            addCriterion("PROLONG_FLAG <=", value, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagIn(List<Short> values) {
            addCriterion("PROLONG_FLAG in", values, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagNotIn(List<Short> values) {
            addCriterion("PROLONG_FLAG not in", values, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagBetween(Short value1, Short value2) {
            addCriterion("PROLONG_FLAG between", value1, value2, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andProlongFlagNotBetween(Short value1, Short value2) {
            addCriterion("PROLONG_FLAG not between", value1, value2, "prolongFlag");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIsNull() {
            addCriterion("ORDER_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIsNotNull() {
            addCriterion("ORDER_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSeqEqualTo(String value) {
            addCriterion("ORDER_SEQ =", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqNotEqualTo(String value) {
            addCriterion("ORDER_SEQ <>", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqGreaterThan(String value) {
            addCriterion("ORDER_SEQ >", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_SEQ >=", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqLessThan(String value) {
            addCriterion("ORDER_SEQ <", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqLessThanOrEqualTo(String value) {
            addCriterion("ORDER_SEQ <=", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqLike(String value) {
            addCriterion("ORDER_SEQ like", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqNotLike(String value) {
            addCriterion("ORDER_SEQ not like", value, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIn(List<String> values) {
            addCriterion("ORDER_SEQ in", values, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqNotIn(List<String> values) {
            addCriterion("ORDER_SEQ not in", values, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqBetween(String value1, String value2) {
            addCriterion("ORDER_SEQ between", value1, value2, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andOrderSeqNotBetween(String value1, String value2) {
            addCriterion("ORDER_SEQ not between", value1, value2, "orderSeq");
            return (Criteria) this;
        }

        public Criteria andSellFlagIsNull() {
            addCriterion("SELL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSellFlagIsNotNull() {
            addCriterion("SELL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSellFlagEqualTo(Short value) {
            addCriterion("SELL_FLAG =", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagNotEqualTo(Short value) {
            addCriterion("SELL_FLAG <>", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagGreaterThan(Short value) {
            addCriterion("SELL_FLAG >", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("SELL_FLAG >=", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagLessThan(Short value) {
            addCriterion("SELL_FLAG <", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagLessThanOrEqualTo(Short value) {
            addCriterion("SELL_FLAG <=", value, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagIn(List<Short> values) {
            addCriterion("SELL_FLAG in", values, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagNotIn(List<Short> values) {
            addCriterion("SELL_FLAG not in", values, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagBetween(Short value1, Short value2) {
            addCriterion("SELL_FLAG between", value1, value2, "sellFlag");
            return (Criteria) this;
        }

        public Criteria andSellFlagNotBetween(Short value1, Short value2) {
            addCriterion("SELL_FLAG not between", value1, value2, "sellFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 21 15:01:00 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PCM_INFO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}