package com.bestpay.ecurrency.operations.dal.model;

import java.util.Date;

public class PcmInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CARD_NO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CARD_SEQ_ID
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String cardSeqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CARD_STATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String cardState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CARD_PWD
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String cardPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CARD_VALUE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Long cardValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CREATED_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.EXP_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Date expDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.EFF_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Date effDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.CARD_TYPE_ID
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Integer cardTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.PROLONG_FLAG
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Short prolongFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.ORDER_SEQ
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private String orderSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PCM_INFO.SELL_FLAG
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    private Short sellFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CARD_NO
     *
     * @return the value of T_PCM_INFO.CARD_NO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CARD_NO
     *
     * @param cardNo the value for T_PCM_INFO.CARD_NO
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CARD_SEQ_ID
     *
     * @return the value of T_PCM_INFO.CARD_SEQ_ID
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getCardSeqId() {
        return cardSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CARD_SEQ_ID
     *
     * @param cardSeqId the value for T_PCM_INFO.CARD_SEQ_ID
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCardSeqId(String cardSeqId) {
        this.cardSeqId = cardSeqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CARD_STATE
     *
     * @return the value of T_PCM_INFO.CARD_STATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getCardState() {
        return cardState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CARD_STATE
     *
     * @param cardState the value for T_PCM_INFO.CARD_STATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCardState(String cardState) {
        this.cardState = cardState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CARD_PWD
     *
     * @return the value of T_PCM_INFO.CARD_PWD
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getCardPwd() {
        return cardPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CARD_PWD
     *
     * @param cardPwd the value for T_PCM_INFO.CARD_PWD
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCardPwd(String cardPwd) {
        this.cardPwd = cardPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CARD_VALUE
     *
     * @return the value of T_PCM_INFO.CARD_VALUE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Long getCardValue() {
        return cardValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CARD_VALUE
     *
     * @param cardValue the value for T_PCM_INFO.CARD_VALUE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCardValue(Long cardValue) {
        this.cardValue = cardValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CREATED_DATE
     *
     * @return the value of T_PCM_INFO.CREATED_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CREATED_DATE
     *
     * @param createdDate the value for T_PCM_INFO.CREATED_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.EXP_DATE
     *
     * @return the value of T_PCM_INFO.EXP_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.EXP_DATE
     *
     * @param expDate the value for T_PCM_INFO.EXP_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.EFF_DATE
     *
     * @return the value of T_PCM_INFO.EFF_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.EFF_DATE
     *
     * @param effDate the value for T_PCM_INFO.EFF_DATE
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.CARD_TYPE_ID
     *
     * @return the value of T_PCM_INFO.CARD_TYPE_ID
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Integer getCardTypeId() {
        return cardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.CARD_TYPE_ID
     *
     * @param cardTypeId the value for T_PCM_INFO.CARD_TYPE_ID
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setCardTypeId(Integer cardTypeId) {
        this.cardTypeId = cardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.PROLONG_FLAG
     *
     * @return the value of T_PCM_INFO.PROLONG_FLAG
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Short getProlongFlag() {
        return prolongFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.PROLONG_FLAG
     *
     * @param prolongFlag the value for T_PCM_INFO.PROLONG_FLAG
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setProlongFlag(Short prolongFlag) {
        this.prolongFlag = prolongFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.ORDER_SEQ
     *
     * @return the value of T_PCM_INFO.ORDER_SEQ
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public String getOrderSeq() {
        return orderSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.ORDER_SEQ
     *
     * @param orderSeq the value for T_PCM_INFO.ORDER_SEQ
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setOrderSeq(String orderSeq) {
        this.orderSeq = orderSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PCM_INFO.SELL_FLAG
     *
     * @return the value of T_PCM_INFO.SELL_FLAG
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public Short getSellFlag() {
        return sellFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PCM_INFO.SELL_FLAG
     *
     * @param sellFlag the value for T_PCM_INFO.SELL_FLAG
     *
     * @mbg.generated Mon Nov 21 15:01:00 CST 2016
     */
    public void setSellFlag(Short sellFlag) {
        this.sellFlag = sellFlag;
    }


    public enum CardState{
        C("20C","可用"),
        F("20F","锁定"),
        W("20W","注销"),
        U("20U","初始");

        String code;

        String desc;

        CardState(String code, String desc) {
            this.code = code;
            this.desc = desc;
        }

        public static String getDesc(String code) {
            for(CardState c:CardState.values()){
                if(c.code.equals(code)){
                    return c.desc;
                }
            }
            return "其他";
        }
    }
}